services:
  db:
    image: postgis/postgis:16-3.4
    container_name: petrosim-db
    environment:
      POSTGRES_DB: petrosim
      POSTGRES_USER: petrosim
      POSTGRES_PASSWORD: petrosim
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./infra/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U petrosim"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
